version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 ecommerce.wsgi:application
    volumes:
      - .:/app
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3  # Persist SQLite database file
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=mysecretkey
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
